name: Rust CI

on:
  pull_request:
  push:

jobs:
  check:
    name: Check Rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - run: cargo check --workspace --all-targets --all-features
